openapi: 3.2.0
info:
  version: '2.0'
  title: Rydership Bundle Items API
  description: 'The Rydership V2 API is open by invite only. Fill out request form here.


    V2 documentation


    V2.1 documentation'
  contact:
    name: Rydership Development Team
    email: tech@whiplash.com
    url: https://www.getwhiplash.com
  x-logo:
    url: https://wl-s3-assets.s3.amazonaws.com/rydership/RyderShip-horizontal-safe-padding.svg
    backgroundColor: '#FFFFFF'
    altText: RyderShip
servers:
- url: ''
  description: Base Path
tags:
- name: Bundle Items
  description: Bundle Items are components that make up a bundle, defining the quantity and relationship of items within product bundles.
paths:
  /api/v2/bundle_items/{id}:
    get:
      operationId: GetApiV2BundleItemsId
      tags:
      - Bundle Items
      summary: Retrieve a bundle item
      description: Get a bundle item
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Get a bundle item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiV2EntitiesBundleItem'
              examples: null
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiSharedEntitiesApiError'
        '403':
          description: forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiSharedEntitiesApiError'
    put:
      operationId: PutApiV2BundleItemsId
      tags:
      - Bundle Items
      summary: Update a bundle item's quantity
      description: Update a bundle item for a bundle
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Update a bundle item for a bundle
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiV2EntitiesBundleItem'
              examples: null
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiSharedEntitiesApiError'
        '403':
          description: forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiSharedEntitiesApiError'
        '422':
          description: unprocessable_entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiSharedEntitiesApiError'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutApiV2BundleItemsIdRequest'
    delete:
      operationId: DeleteApiV2BundleItemsId
      tags:
      - Bundle Items
      summary: Destroy a bundle item
      description: Destroy a bundle item for a bundle
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: Successfully deleted
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiSharedEntitiesApiError'
        '403':
          description: forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiSharedEntitiesApiError'
        '422':
          description: unprocessable_entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiSharedEntitiesApiError'
components:
  schemas:
    PutApiV2BundleItemsIdRequest:
      type: object
      properties:
        quantity:
          type: integer
          format: int32
          description: the bundle item quantity
    ApiV2EntitiesBundleItem:
      type: object
      title: V2
      properties:
        id:
          type: integer
          format: int32
          description: the bundle item id
        parent_item_id:
          type:
          - integer
          - 'null'
          format: int32
          description: the bundle item parent item id (admins only)
        item_id:
          type:
          - integer
          - 'null'
          format: int32
          description: the bundle item item id
        bundle_id:
          type:
          - integer
          - 'null'
          format: int32
          description: the bundle item bundle id (admins only)
        quantity:
          type:
          - integer
          - 'null'
          format: int32
          description: the bundle item quantity
        max_per_package:
          type:
          - integer
          - 'null'
          format: int32
          description: the bundle item max per package (admins only)
        created_at:
          type:
          - string
          - 'null'
          format: date-time
          description: the bundle item creation date and time
        updated_at:
          type:
          - string
          - 'null'
          format: date-time
          description: the bundle item last update date and time
        item_quantity:
          type: string
        item_name:
          type: string
      additionalProperties: false
    ApiSharedEntitiesApiError:
      type: object
      title: Shared
      properties:
        message:
          type: string
          description: error message
      additionalProperties: false
